
<html>
  <head>
    <title>Lab 02 - Graded Solution</title>
  </head>
  <body>
    <h1>Lab 02 - Graded Solution</h1>
    <p><b>You scored 0% = 0.0 points for this lab.</b></p>
    <ul>
      <li><b>A smaller test case for your ngram function.</b>
      <ul>
      <li>Grade Percentage: 10</li>
      <li>Your solution failed this test case! taking 0.105 sec</Li>
<li><pre>AssertionError: Expected {'i': [('really', 'really')], 'really': [('really', 'like'), ('like', 'cake.')]} but got {'i': [('really',), ('really', 'really')], 'really': [('really',), ('really', 'like'), ('like',), ('like', 'cake.')]}</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 48, in wrapper
    result = test_function(module, *args, **kwargs)
  File "/var/folders/f7/xnz8v_b13td37s3k4w8t5j2h0000gn/T/tmp_j8_8ocn/lab02-test.py", line 40, in test1_1
    assertEquals(m.module.compute_ngrams(simple_toks, n=3),
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/assertions.py", line 29, in assertEquals
    raise AssertionError(message)
AssertionError: Expected {'i': [('really', 'really')], 'really': [('really', 'like'), ('like', 'cake.')]} but got {'i': [('really',), ('really', 'really')], 'really': [('really',), ('really', 'like'), ('like',), ('like', 'cake.')]}
</pre></li>
      </ul>
      </li>
      <li><b>A small test case for your ngram function with Romeo & Juliette.</b>
      <ul>
      <li>Grade Percentage: 10</li>
      <li>Your solution failed this test case! taking 0.124 sec</Li>
<li><pre>AssertionError: Expected [('sick', 'and', 'green'), ('fools', 'do', 'wear')] but got [('sick',), ('sick', 'and'), ('sick', 'and', 'green'), ('fools',), ('fools', 'do'), ('fools', 'do', 'wear')]</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 48, in wrapper
    result = test_function(module, *args, **kwargs)
  File "/var/folders/f7/xnz8v_b13td37s3k4w8t5j2h0000gn/T/tmpdtpyl44z/lab02-test.py", line 52, in test1_1
    assertEquals(dct['but'], [('sick', 'and', 'green'), ('fools', 'do', 'wear')])
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/assertions.py", line 29, in assertEquals
    raise AssertionError(message)
AssertionError: Expected [('sick', 'and', 'green'), ('fools', 'do', 'wear')] but got [('sick',), ('sick', 'and'), ('sick', 'and', 'green'), ('fools',), ('fools', 'do'), ('fools', 'do', 'wear')]
</pre></li>
      </ul>
      </li>
      <li><b>Test your ngram function on Peter Pan.</b>
      <ul>
      <li>Grade Percentage: 30</li>
      <li>Your solution failed this test case! taking 1.130 sec</Li>
<li><pre>AssertionError: Expected [('passes,', 'but'), ('that', 'happened'), ('would', 'have'), ('was', 'in'), ('passed', 'him,'), ('is', 'about'), ('climbing', 'it.'), ('that', 'was'), ('pass', 'by'), ('and', 'let'), ('was', 'among'), ('was', 'waiting')] but got [('passes,',), ('passes,', 'but'), ('that',), ('that', 'happened'), ('would',), ('would', 'have'), ('was',), ('was', 'in'), ('passed',), ('passed', 'him,'), ('is',), ('is', 'about'), ('climbing',), ('climbing', 'it.'), ('that',), ('that', 'was'), ('pass',), ('pass', 'by'), ('and',), ('and', 'let'), ('was',), ('was', 'among'), ('was',), ('was', 'waiting')]</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 48, in wrapper
    result = test_function(module, *args, **kwargs)
  File "/var/folders/f7/xnz8v_b13td37s3k4w8t5j2h0000gn/T/tmp4tckb60c/lab02-test.py", line 70, in test1_3
    assertEquals(dct['crocodile'],
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/assertions.py", line 29, in assertEquals
    raise AssertionError(message)
AssertionError: Expected [('passes,', 'but'), ('that', 'happened'), ('would', 'have'), ('was', 'in'), ('passed', 'him,'), ('is', 'about'), ('climbing', 'it.'), ('that', 'was'), ('pass', 'by'), ('and', 'let'), ('was', 'among'), ('was', 'waiting')] but got [('passes,',), ('passes,', 'but'), ('that',), ('that', 'happened'), ('would',), ('would', 'have'), ('was',), ('was', 'in'), ('passed',), ('passed', 'him,'), ('is',), ('is', 'about'), ('climbing',), ('climbing', 'it.'), ('that',), ('that', 'was'), ('pass',), ('pass', 'by'), ('and',), ('and', 'let'), ('was',), ('was', 'among'), ('was',), ('was', 'waiting')]
</pre></li>
      </ul>
      </li>
      <li><b>Test case for random passage generation.</b>
      <ul>
      <li>Grade Percentage: 50</li>
      <li>Your solution failed this test case! taking 0.115 sec</Li>
<li><pre>AssertionError: Expected like cake. i really really really really like cake. i but got None</pre></li>
<li><pre>Traceback (most recent call last):
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/execution_base.py", line 60, in call_test_function
    test_function(
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/core.py", line 48, in wrapper
    result = test_function(module, *args, **kwargs)
  File "/var/folders/f7/xnz8v_b13td37s3k4w8t5j2h0000gn/T/tmpo_5thoh4/lab02-test.py", line 93, in test1_3
    assertEquals(m.module.gen_passage(m.module.compute_ngrams(simple_toks), 10),
  File "/Users/lord_pretzel/.pyenv/versions/3.9.0/lib/python3.9/site-packages/grader-0.0.1-py3.9.egg/grader/assertions.py", line 29, in assertEquals
    raise AssertionError(message)
AssertionError: Expected like cake. i really really really really like cake. i but got None
</pre></li>
      </ul>
      </li>
    </ul>
  </body>
</html>
